import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="p-6">
      <body className={inter.className}>
        <nav>
          <ul className="flex gap-4 ">
            <li>
              <Link href="/">Home</Link>
            </li>
            <li>
              <Link prefetch={false} href="/about">About</Link>
            </li>
            <li>
              <Link href="/service">Service</Link>
            </li>
            <li>
              <Link href="/about/mission">Mission</Link>
            </li>
            <li>
              <Link href="/a">404 Pgae</Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
