import { Poppins} from 'next/font/google'
import Link from 'next/link'
import './globals.css'

const poppins = Poppins({ subsets: ['latin'], weight: '400' })


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="p-6">
      <body className={poppins.className}>
        <nav>
          <ul className="flex gap-4 ">
            <li>
              <Link href="/">Home</Link>
            </li>
            <li>
              <Link prefetch={false} href="/about">
                About
              </Link>
            </li>
            <li>
              <Link href="/service">Service</Link>
            </li>
            <li>
              <Link href="/about/mission">Mission</Link>
            </li>
            <li>
              <Link href="/a">404 Pgae</Link>
            </li>
            <li>
              <Link href="/blogs">Blog</Link>
            </li>
            <li>
              <Link href="/post">Post</Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  )
}
